apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cilium-stack-walkthrough
  region: us-west-2
managedNodeGroups:
- name: ng-1
  privateNetworking: true
  taints: 
  - key: "node.cilium.io/agent-not-ready"
    value: "true"
    effect: "NoExecute"
  desiredCapacity: 3
  minSize: 3
  maxSize: 4
